org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
craftwire_version=0.1.0
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.161.0+26.2
log4j_version=2.26.0
paper_api_version=26.2.build.130-stable
paper_build=130
paper_sha256=715cd6633db27b2c05ce6efd2d477330ebae8a4f668cf0459fcaf434c4720fba
graal_version=25.0.4
