pluginManagement {
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'PaperMC'; url = 'https://repo.papermc.io/repository/maven-public/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'craftwire'
include 'agent-core', 'agent-fabric', 'agent-paper', 'test-fixtures'
